"""initial

Revision ID: ef82d2191c91
Revises: 1f4ab4cb83c7
Create Date: 2023-11-02 10:07:12.653558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef82d2191c91'
down_revision: Union[str, None] = '1f4ab4cb83c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('book_quantity', sa.Integer(), nullable=False))
    op.add_column('order', sa.Column('book_price', sa.Float(), nullable=False))
    op.add_column('order', sa.Column('book.id', sa.Integer(), nullable=True))
    op.drop_column('order', 'pizza_quantity')
    op.drop_column('order', 'pizza_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('pizza_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('pizza_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('order', 'book.id')
    op.drop_column('order', 'book_price')
    op.drop_column('order', 'book_quantity')
    # ### end Alembic commands ###
